<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<div class="block ttr_block <?php /* @escapeNotVerified */ echo $block->getBlockCss(); ?>">
    <div class="title  ttr_block_header <?php /* @escapeNotVerified */ echo $block->getBlockCss();?>-title" data-mage-init='{"toggleAdvanced": {"toggleContainers": "#<?php /* @escapeNotVerified */ echo $block->getBlockCss(); ?>", "selectorsToggleClass": "active"}}'>
        <h3 class="ttr_block_heading">
        <img alt="Blockicon" src="<?php  echo $block->getViewFileUrl('images/blockicon.png'); ?>">
        <?php /* @escapeNotVerified */ echo $block->getBlockTitle(); ?></h3>
    </div>
    <div class="content ttr_block_content <?php /* @escapeNotVerified */ echo $block->getBlockCss(); ?>-content" id="<?php /* @escapeNotVerified */ echo $block->getBlockCss(); ?>">
        <?php echo $block->getChildHtml(); ?>
    </div>
</div>
