<a href="http://www.facebook.com/TemplateToaster" class="ttr_footer_facebook " target="_self" >
</a>
<a href="http://www.templatetoaster.com"class="ttr_footer_linkedin " target="_self" >
</a>
<a href="http://twitter.com/templatetoaster"class="ttr_footer_twitter " target="_self" >
</a>
<div id="ttr_footer_designed_by_links">
<a href="http://templatetoaster.com" target="_self" >
Magento Theme
</a>
<span id="ttr_footer_designed_by">
Designed With TemplateToaster
</span>
</div>
