<?php $h=  $this->getRequest()->getFullActionName(); if($h == 'cms_index_index'){?>
<div class="margin_collapsetop"></div>
<div id="ttr_slideshow_inner">
<ul>
<li id="Slide0" class="ttr_slide" data-slideEffect="None">
<a href="http://templatetoaster.com/"></a>
<div class="ttr_slideshow_last">
<div class="ttr_slideshow_element_alignment container" data-begintime="0" data-effect="None" data-easing="linear" data-slide="None" data-duration="0">
</div>
</div>
</li>
<li id="Slide1" class="ttr_slide" data-slideEffect="Fade">
<a href="http://templatetoaster.com/"></a>
<div class="ttr_slideshow_last">
<div class="ttr_slideshow_element_alignment container" data-begintime="0" data-effect="None" data-easing="linear" data-slide="None" data-duration="0">
</div>
</div>
</li>
</ul>
</div>
<div class="ttr_slideshow_in">
<div class="ttr_slideshow_last">
<div class="ttr_slideshow_element_alignment container">
</div>
<div id="nav"></div>
<div class="ttr_slideshow_logo">
</div>
<div class="ttr_stickyslideshowshape1">
<div class="html_content"><p style="line-height:5.41em;"><span style="font-family:'ABeeZee','Arial';font-size:4.643em;color:rgba(255,255,255,1);">Best Bike</span></p><p style="line-height:5.41em;"><span style="font-family:'ABeeZee','Arial';font-size:4.643em;color:rgba(255,255,255,1);">Online Store</span></p></div>
</div>
</div>
</div>
<?php } ?>
