<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Shopping cart totals template
 * @var $block \Magento\Checkout\Block\Cart\Totals
 */
?>
<div id="cart-totals" class="cart-totals col-xl-12 col-lg-12 " data-bind="scope:'block-totals'">
<div class="ttr_prodsigninheading"  style="padding:5px 0px;margin:0px;">Total</div>
<hr>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
            {
                "#cart-totals": {
                    "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
                }
            }
    </script>
     <hr>
</div>
